# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'test7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test7
  pod 'Theo'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end
